### ISSUE TITLE
Add functionality to change throughput of collection after creation

### ISSUE THREAD

**Issue by ElvaHuang** [Azure/azure-documentdb-python#101]
My application heavily relies on pydocumentdb to interact with cosmos. We're looking for the ability to change throughput of a collection after its creation, similar to [https://docs.microsoft.com/en-us/azure/cosmos-db/set-throughput#set-throughput-sdk].  

I can't seem to find it. Am I missing something? If not, can you add this important functionality? Thank you.

**Comment by moderakh** [comment]
After the collection is created, you can query for the collection's offer which indicates the throughput after that you can replace the existing offer.

The following code shows how to find the relevant collection offer:
https://github.com/Azure/azure-documentdb-python/blob/master/test/crud_tests.py#L253-L257

After that you should replace the new offer as 'offerThroughput' in the retrieved offer and try to replace it.

https://github.com/Azure/azure-documentdb-python/blob/master/test/crud_tests.py#L3615

When replacing you only need to modify 'offerThroughput' of the offer

**Comment by ElvaHuang** [comment]
Worked! Great! Thanks a lot.
