### ISSUE TITLE
Samples need to be improved

### ISSUE THREAD

**Issue by HITliuyu** [Azure/azure-documentdb-python#108]
This is not an issue, however, I strongly suggest maintainers provide more samples to us which would help python developers to have a better understanding of how to use this SDK. E.g., in sample folder, documents management sample is missing. As stated in #87 the documentation can hardly be understood since it is not complete at all, thus we really need good samples to walk us through these APIs. I know different SDKs have their own development plans and milestones, but compared with JaveScript and C#, this python SDK really need to be improved.

**Comment by moderakh** [comment]
Hi @HITliuyu Thanks for your comment. We are in the process of improving samples.
Please see an active effort for more samples:
https://github.com/Azure/azure-documentdb-python/pull/107

**Comment by HITliuyu** [comment]
Hi @moderakh ，
thank you for your very quick reply! I will definitely check that.

Regards,
Yu

**Comment by bacongobbler** [comment]
looks like this can be closed now that the samples have been merged.

**Comment by srinathnarayanan** [comment]
Closing this since PR has been merged
