### ISSUE TITLE
Documentation styling is broken 

### ISSUE THREAD

**Issue by jdk514** [Azure/azure-documentdb-python#110]
The styling of the [pydocumentdb documentation](http://azure.github.io/azure-documentdb-python/) appears to be broken.

**Comment by vchalmel** [comment]
No it's not, but the online github version appears "blank" because it's not intended to be browsed like that. If you follow the instructions (given at the link you provided), to compile the doc on your side, it will generate local files with correct styling/browsing, etc.

**Comment by mimig1** [comment]
The styling of http://azure.github.io/azure-documentdb-python/ (with paragraph marks showing, etc) is as expected.
