### ISSUE TITLE
How to serialize a dict type object when creating a document using CreateDocument ?

### ISSUE THREAD

**Issue by moriaki3193** [Azure/azure-documentdb-python#115]
I submit a issue for the first time.

I am new to Cosmos DB and  I have a question related to creating a `embedded ( or nested)` document.
I am trying to POST and create a document represented as below

```Python
{
  "id":  "123",
  "title": "aaa",
  "desc": "bbb",
  "steps": [
    { "foo": "1", "bar": "xxx" },
    { "foo": "2", "bar": "yyy" },
  ]
}
```

However, an error occurs like below...

```
{"code":"BadRequest","message":"Message: {\"Errors\":[\"The request payload is invalid. Ensure to provide a valid request payload.\"]} ... }
```

I read [this article](https://docs.microsoft.com/en-us/rest/api/documentdb/http-status-codes-for-documentdb) and noticed that the request body is a JSON and it's invalid.

So, I tried to serialized entire document as a string, however, another error occurs.

```
File "/path/to/pydocumentdb/document_client.py", line 2760, in __ValidateResource
  id = resource.get('id')
AttributeError: 'str' object has no attribute 'get'
```

Finally, I tried to serialized the `steps` field only so that the document can be represented as a dict like below.

```Python
doc = {
  "id":  "123",
  "title": "aaa",
  "desc": "bbb",
  "steps": [
    { "foo": "1", "bar": "xxx" },
    { "foo": "2", "bar": "yyy" },
  ]
}
doc["steps"] = json.dumps(doc["steps"])
```

This approach is not good because the type of `steps` in the document inserted into Document DB is still string.
I would like to convert `steps` field into dict type...

I am at a loss what to do next.

Is there any solution to this problem?

**Comment by HussainMir** [comment]
Hi, just a random guess, 
```
doc = {
  "id":  "123",
  "title": "aaa",
  "desc": "bbb",
  "steps": [
    { "foo": "1", "bar": "xxx" },
    { "foo": "2", "bar": "yyy" }, # can we try once without the , at the end?
  ]
}
```
Also, request you to once go through the samples demonstrating [document management](https://github.com/Azure/azure-documentdb-python/blob/master/samples/DocumentManagement/Program.py).

Regards.

**Comment by moriaki3193** [comment]
I found that `np.NaN` caused the error.
