### ISSUE TITLE
Wrong brackets position closing causes document management code to fail

### ISSUE THREAD

**Issue by dkarmon** [Azure/azure-documentdb-python#118]
Noticed a small typo in the [document management tutorial](https://raw.githubusercontent.com/Azure/azure-documentdb-python/master/samples/DocumentManagement/Program.py) that causes the code to fail.
It seems that the brackets in ReadDocuments function were closed too early making the second parameter (param dictionary) to be addressed as a second parameter of the list function (which should receive only one input argument).

Line 89:
`documentlist = list(client.ReadDocuments(collection_link**)**, {'maxItemCount': 10})`

sholud be
`documentlist = list(client.ReadDocuments(collection_link, {'maxItemCount': 10}**)**)`

**Comment by moderakh** [comment]
@dkarmon thank you very much for helping us in reporting this issue.

Now that you found this, I wonder if you are interested in sending a Pull Request for fixing it. We will merge PR and it will be your contribution.

Thanks.

**Comment by srinathnarayanan** [comment]
PR has been merged. Closing this issue.
