### ISSUE TITLE
Support Partitioning?

### ISSUE THREAD

**Issue by yokawasa** [Azure/azure-documentdb-python#21]
Thank you for awesome python SDK for documentdb!

I'm wondering if you are going to support partitioning like .NET SDK does
http://azure.microsoft.com/blog/2015/04/30/announcing-partitioning-support-in-the-documentdb-sdk/

**Comment by ryancrawcour** [comment]
This is certainly something that is planned for a future release of the Python SDK. Just don't have a committed timeline for this. 

We would however welcome contributions if this is something you would like to work on.

**Comment by ryancrawcour** [comment]
This has been completed with the release of 1.5.0
https://azure.microsoft.com/en-us/documentation/articles/documentdb-sdk-python/

**Comment by yokawasa** [comment]
That's awesome! Thank you.
