### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by colinmcintosh** [Azure/azure-documentdb-python#32]
Are there plans to include support for Python 3?

**Comment by ryancrawcour** [comment]
Yes, there are. No committed date as yet though. We'd be more than happy to accept a PR.

**Comment by rnagpal** [comment]
@colinmcintosh We now support Python3 with SDK release 2.0.0

**Comment by colinmcintosh** [comment]
Woohoo!! Thanks for the update @rnagpal
