### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by edevil** [Azure/azure-documentdb-python#48]
Is it planned?

**Comment by rnagpal** [comment]
We will look into what it takes to have a Python 3 package for DocumentDB.

Is there any specific reason/requirement you have for Python 3?

**Comment by edevil** [comment]
Not anything specific, we just don't use Python 2 anymore.

**Comment by rnagpal** [comment]
Thanks for the feedback. I'll update you in the next few weeks how that is going.

**Comment by dy-wang** [comment]
Hi, I wanted to see if there's any update on this? Thanks.

**Comment by rnagpal** [comment]
Yes, we are in final stages of verifying Python 3 support and will be releasing within a week or so.

**Comment by rnagpal** [comment]
@edevil @dy-wang We have released 2.0.0 release for Python SDK that has the support for Python3 along with Python2.
