### ISSUE TITLE
Multi-threaded DocumentClient

### ISSUE THREAD

**Issue by jbarguil** [Azure/azure-documentdb-python#50]
Hi, sorry if this isn't the best place but I have a question regarding `pydocumentdb.document_client.DocumentClient`.

I'm building an API based on flask, and I'd like to know what is the best approach:
  - Should I keep a single instance of DocumentClient OR
  - Should I instantiate it several times, once per request?

In other words, is `DocumentClient` thread-safe?

Thanks in advance!

**Comment by rnagpal** [comment]
@jbarguil : Just have a single instance of DocumentClient.

DocumentClient Python SDK module is single threaded.

**Comment by jbarguil** [comment]
@rnagpal Thank you!
